services:
  application:
    container_name: chronos-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    volumes:
      - ./src/main/resources/certs:/app/certs  # Mount the local 'certs' directory inside the container
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge