version: '3.8'
services:
  mysql:
    container_name: auth-mysql
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
    networks:
      - stack
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin1234" ]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  application:
    container_name: chronos-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    networks:
      - stack
    depends_on:
      mysql:
        condition: service_healthy

networks:
  stack:
    name: stack
    driver: bridge