services:
  application:
    container_name: chronos-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge